### ISSUE TITLE
fix typo

### ISSUE THREAD

**Issue by SOHELAHMED7** [SOHELAHMED7/crudsh#1]
file take_menu_input_from_user.sh contains type

fnuction should be fixed to functions

**Comment by akshaypjoshi** [comment]
Typo fixed in commit [89940ff](https://github.com/SOHELAHMED7/crudsh/pull/2/commits/89940ff135e7e380b4c93a08d826ef3e283e55e2).

**Comment by SOHELAHMED7** [comment]
@akshaypjoshi https://github.com/SOHELAHMED7/crudsh/pull/2#issuecomment-489507753
